### PR TITLE
Optimize conditional expressions

### LINKED ISSUE #1112: CSS Parsing Exception:
**Describe the bug**
When compiling CSS after upgrading from @compiled/webpack-loader 0.8.0 to 0.8.3, I get the following error on build:

```
Input CSS: {

    border: none;
    outline: none;
    background: #fd5b47;
    color: #fff;
    user-select: none;
    text-align: center;
    text-decoration: none;
    text-transform: uppercase;1.4rem;
    font-size: ;;
    font-weight: 700;
    line-height: 1.4;
    transition: color .2s, background-color .2s;
    border-radius: 2rem;
    box-sizing: border-box;
    appearance: none;
    display: inline-block;;

    :hover, :focus {
        background: #f0a202;
    }

    :disabled, :hover:disabled {
        background: #cdd7d6;
    }
;
  }

  Exception: <css input>:9:31: Unknown word
    at runMicrotasks (<anonymous>)
```

with this source

image

### PR DESCRIPTION
**Pull request by at-nathan**
Resolves #1112 

Another attempt at evaluating conditional CSS into separate CSS classes.
This PR limits the optimization to scenarios like:
```
color: ${({ isSelected }) => isSelected ? 'green' : 'black' };
```
Scenarios where conditionals have sibling expressions or apart of strings will fallback to CSS variables. For example:
```
/* Technique cannot be applied to conditions like this */
height: calc(100% - ${identifier} - ${conditionalExpression});

/* Strings are unpredictable and can break parsing */
content: 'Code example: ${conditionalExpression};';
```

Additional fixes:
- Conditional CSS not working in nested selectors
- Conditional CSS breaking in selectors with static styles
- Conditional CSS breaking with duplicate CSS property
- Conditional CSS breaking when condition test contains an object

### CODE REVIEW

File: packages/babel-plugin/src/utils/css-builders.ts [hunk 1]
```diff
@@ -656,13 +659,12 @@ const extractTemplateLiteral = (node: t.TemplateLiteral, meta: Metadata): CSSOut
...
+    const doesExpressionContainCssBlock =
       t.isObjectExpression(interpolation) ||
       isCompiledCSSTaggedTemplateExpression(interpolation, meta.state) ||
-      isCompiledCSSCallExpression(interpolation, meta.state) ||
-      (t.isArrowFunctionExpression(nodeExpression) &&
-        t.isConditionalExpression(nodeExpression.body))
-    ) {
+      isCompiledCSSCallExpression(interpolation, meta.state);
+
+    if ((!isMidStatement && doesExpressionContainCssBlock) || doesExpressionHaveConditionalCss) {
```
Comment (at-nathan) [inline packages/babel-plugin/src/utils/css-builders.ts:667]: Without the `isMidStatement` this was breaking on styles like:
`${({ color }) => (color && COLOR_MAP[color] ? COLOR_MAP[color] : colors.B400)};`
Because it `color` is dynamic, Compiled can only work out what `COLOR_MAP` is. It saw it was an `ObjectExpression` and spread the whole Object into the stylesheet.

We might want to consider returning the original node/expression if we can't evaluate it the whole way through for certain expression types.

**Review by JakeLane — APPROVED** [review]

**Review by JakeLane — APPROVED** [review]
