### PR TITLE
1295 - Improve support for computed object property keys

### LINKED ISSUE #1295: Can't use more than one import in template literal as object property key
**Describe the bug**
```
import { hiddenClass } from './hidden';
import { itemClass } from './item';

// Output selector becomes .hidden, itemClass
const Comp = styled.div({
  [`${hiddenClass}, ${itemClass}`] { ... },
});
```

### PR DESCRIPTION
**Pull request by at-nathan**
Resolves #1295
- Fixes bug where more than one import cannot be used in template literal object property key
- Support string binary operation in object property keys

### CODE REVIEW

**Review by JakeLane — APPROVED** [review]

File: packages/babel-plugin/src/utils/object-property-to-string.ts [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+    const rightValue = expressionToString(right, meta);
+
+    return `${leftValue}${rightValue}`;
+  }
+
+  throw new Error(`Cannot use ${operator} for string operation. Use + for string concatenation`);
+};
+
+const expressionToString: ExpressionToString = (expression, meta) => {
+  // handles {'key-name': 'value'} or {1: 'value'}
```
Comment (pancaspe87) [inline packages/babel-plugin/src/utils/object-property-to-string.ts:52]: Not sure if we should also handle `isNumericLiteral`. 
I can't think of any css property defined with a number, or any scenario where a selector could be a number. Keeping it shouldn't cause any issue though.

@JakeLane, @liamqma  any thoughts on this?

Comment (at-nathan) [reply packages/babel-plugin/src/utils/object-property-to-string.ts:52]: Yeah true, when I was writing it I was thinking about all Objects in general 😅 Maybe number should be unsupported so it can throw an error?

Comment (at-nathan) [reply packages/babel-plugin/src/utils/object-property-to-string.ts:52]: On second thought, I think we do need to keep the numeric evaluation, otherwise we can do things like:
`['field' + 1]: { ... }`

Comment (pancaspe87) [reply packages/babel-plugin/src/utils/object-property-to-string.ts:52]: I thought it was checking for numbers only. Yeahh, we should keep it if it deals with alphanumerics :)
