### PR TITLE
fix: fixes prefix interpolations on template literals

### LINKED ISSUE #400: Negative numbers breaking property expanding
```js
export const Wrapper = styled.section`
    margin: 0 -${props => props.gridSize * 5}px ${props => props.gridSize * 4}px -${props => props.gridSize * 5}px;
`;
```

Results in

```css
--_1l3fmvo: 0 -40px;
--_gbo7pc: 32px;

._18u0vsak {
    margin-left: var(--_gbo7pc);
}

._otyr1xn1 {
    margin-bottom: var(--_1l3fmvo);
}

._2hwxvsak {
    margin-right: var(--_gbo7pc);
}

._19pk1xn1 {
    margin-top: var(--_1l3fmvo);
}
```

Margin left is wrong.

### PR DESCRIPTION
**Pull request by madou**
Closes #400

### CODE REVIEW

File: packages/css/src/utils/string-interpolations.tsx [hunk 1]
```diff
@@ -71,14 +71,16 @@ export const cssBeforeInterpolation = (css: string): BeforeInterpolation => {
     };
   }
 
-  if (!css.match(/:|;/) && !css.includes('(')) {
+  if (!css.match(/:|;/) && !css.includes('(') && !css.includes(' ')) {
```
Comment (DarkPurple141) [inline packages/css/src/utils/string-interpolations.tsx:74]: eesh

**Review by DarkPurple141 — APPROVED** [review]

File: packages/css/src/utils/string-interpolations.tsx (hunk 1 above)
Comment (madou) [reply packages/css/src/utils/string-interpolations.tsx:74]: thanks i hate it

**Review by DarkPurple141 — APPROVED** [review]
