### PR TITLE
Webpack loader

### LINKED ISSUE #344: Modifying values outside of a module doesn't update the component styles
**Describe the bug**

When developing (using Parcel) in a component and modifying some properties outside of the module that are imported - don't end up recompiling the component - thus they don't get updated.

```jsx
// colors.tsx
export const heroBackground = 'linear-gradient(120deg,blue 0%, #8fd3f4 100%)';

// hero.tsx
import React from 'react';
import '@compiled/core';
import { heroBackground } from '../utils/colors';

export const Hero = ({ children }: { children: React.ReactNode }) => {
  return (
    <div
      css={{
        background: heroBackground,
      }}>
      {children}
    </div>
  );
};
```

What's worse - sometimes you get into a state where it just won't update. In this case is it our caching behaviour, or is it the bundler? Both?

**To Reproduce**

1. Use code above
1. Run with your favourite bundler
1. Update hero background
1. Notice that the component doesn't have the updated color
1. Now modify hero component
1. Notice that is now is updated as expected

**Expected behavior**

It should update the component color without needing the modify the component file.

**Additional context**

Not sure what we can do here. Is it possible to fix this if we create a bundler plugin to make sure any depending module gets re-transformed if something changes?

**Questions**

- Does this also affect Webpack
- How can we force a bundler to recompile a consuming module (so it runs the Babel plugin over it, again)

### PR DESCRIPTION
**Pull request by madou**
Fix #344 for Webpack users.

**TODO**

- [x] Creation of `transform` export in babel plugin
- [x] Async webpack loader
- [x] Single pass caching
- [x] Webpack dev server rebuilds and shows changes after modifying statically evaluated module
- [x] Move babel plugin to its own file and re-export through `index.tsx`
- [x] Error handling
- [x] Static evaluation not working
- [x] Included files callback tested and working
- [x] Loader tests
- [x] Documentation
- [x] Configuration pass through

**Outstanding thoughts**

- Can we hook into a single babel pass instead of doing another with our `transform` function? Parcel has this capability.

**Related**

- Docs change here https://github.com/compiled/website/pull/54

### CODE REVIEW

**Comment by madou** [comment]
@pgmanutd want to do an early review?

To run locally:

```bash
git checkout webpack-plugin-spike
yarn
yarn start:webpack
```

File: packages/babel-plugin/src/babel-plugin.tsx [hunk 1]
```diff
@@ -0,0 +1,195 @@
+import { declare } from '@babel/helper-plugin-utils';
```
Comment (madou) [inline packages/babel-plugin/src/babel-plugin.tsx:1]: this file hasn't changed - its just been renamed.

File: packages/babel-plugin/src/index.tsx [hunk 2]
```diff
@@ -1,185 +1,2 @@
...
-          return;
-        }
-
-        visitCssPropPath(path, { state, parentPath: path });
-      },
-    },
-  };
-});
+export { default } from './babel-plugin';
+export { transform } from './transform';
```
Comment (madou) [inline packages/babel-plugin/src/index.tsx:2]: so we can transform directly if needed. currently using this in webpack loader - however it might not be needed in parcel. maybe.

File: packages/babel-plugin/src/types.tsx [hunk 3]
```diff
@@ -11,8 +11,12 @@ export interface PluginOptions {
 
   /**
    * Whether to use the cache or not. Will make subsequent builds faster.
+   *
+   * - `true` caches for the duration of the node run (useful for single builds)
+   * - `"file-pass"` caches per file pass (useful for watch mode)
+   * - `false` turns caching off
    */
-  cache?: boolean;
+  cache?: boolean | 'file-pass';
```
Comment (madou) [inline packages/babel-plugin/src/types.tsx:19]: not too sure if this is needed anymore. keeping cache as `true` doesn't seem to affect the run (things still change as expected).

**Comment by pgmanutd** [comment]
> @pgmanutd want to do an early review?
> 
> To run locally:
> 
> ```shell
> git checkout webpack-plugin-spike
> yarn
> yarn start:webpack
> ```

Noice. I ll have a look 😃. I looked it once few days back. I think lot has changed since then.

**Comment by madou** [comment]
@pgmanutd I'm going to merge this to use in the parcel spike (want to push this out anyway 😄) - if you can have a review and we can change things in a follow up PR if needed 👍

File: packages/babel-plugin/src/transform.tsx [hunk 4]
```diff
@@ -0,0 +1,33 @@
...
+ * @param code Code to transform
+ * @param opts Userland options
+ */
+export async function transformAsync(code: string, opts: TransformOpts): Promise<TransformResult> {
+  const includedFiles: string[] = [];
+
+  const result = await babelTransformAsync(code, {
+    babelrc: false,
+    configFile: false,
+    filename: opts.filename,
```
Comment (madou) [inline packages/babel-plugin/src/transform.tsx:23]: will break TS & Flow I think. Need to infer some config from userland.

**Comment by pgmanutd** [comment]
> @pgmanutd I'm going to merge this to use in the parcel spike (want to push this out anyway 😄) - if you can have a review and we can change things in a follow up PR if needed 👍

No worries. Later it is 😄
