### PR TITLE
fix: fixes automatic jsx transform not working

### LINKED ISSUE #349: Test with new jsx automatic transform
Currently unsure if we need to do anything to make it work.

### PR DESCRIPTION
**Pull request by madou**
Makes some changes to ensure jsx automatic mode works. Don't merge until #420 is merged.

Currently the automatic behavior is behind a babel plugin option instead of trying to infer - inferring was more trouble than its worth TBH.

**Question**

- What should we call the option? The _behaviour_ is to just add `React` if its missing. Currently it's called `importReact`.

Closes #349

### CODE REVIEW

File: examples/class-names-dynamic.tsx [hunk 1]
```diff
@@ -55,7 +54,7 @@ const ClassNamesArray = ({ weight }: { weight: number }) => (
   </ClassNames>
 );
 
-export const Object = () => <ClassNamesObject color="pink" />;
```
Comment (madou) [inline examples/class-names-dynamic.tsx:58]: interestingly webpack adds an `Object` check now which made this stack overflow

File: package.json [hunk 2]
```diff
@@ -34,12 +34,13 @@
     "postinstall": "npx yarn-deduplicate"
   },
   "devDependencies": {
+    "@babel/plugin-transform-react-jsx-self": "^7.12.1",
```
Comment (madou) [inline package.json:37]: had to add these for some reason - wasn't found otherwise.

File: package.json [hunk 3]
```diff
@@ -34,12 +34,13 @@
...
+    "@babel/plugin-transform-react-jsx-source": "^7.12.1",
     "@babel/preset-env": "^7.11.0",
     "@babel/preset-react": "^7.10.4",
     "@babel/preset-typescript": "^7.10.4",
     "@compiled/jest": "*",
     "@compiled/react": "*",
-    "@emotion/core": "^10.1.1",
```
Comment (madou) [inline package.json:42]: removed the emotion test because i'd need to upgrade it to v11 for the new automatic stuff. rather just remove.

File: packages/babel-plugin/src/__tests__/index.test.tsx [hunk 4]
```diff
@@ -80,10 +80,11 @@ describe('babel plugin', () => {
     expect(output?.code).toMatchInlineSnapshot(`
       "/* File generated by @compiled/babel-plugin v0.0.0 */
 
+      import { forwardRef } from 'react';
```
Comment (madou) [inline packages/babel-plugin/src/__tests__/index.test.tsx:83]: forward ref now imported as a named import.

File: packages/babel-plugin/src/index.tsx [hunk 5]
```diff
@@ -90,11 +90,17 @@ export default declare<State>((api) => {
...
-          if (!path.scope.getBinding('React')) {
+          const shouldImportReact = state.opts.importReact === undefined || state.opts.importReact;
+          if (shouldImportReact && !path.scope.getBinding('React')) {
             // React is missing - add it in at the last moment!
             path.unshiftContainer('body', template.ast(`import * as React from 'react'`));
           }
 
+          if (state.compiledImports.styled && !path.scope.getBinding('forwardRef')) {
+            // forwardRef is missing - add it in at the last moment!
+            path.unshiftContainer('body', template.ast(`import { forwardRef } from 'react'`));
```
Comment (madou) [inline packages/babel-plugin/src/index.tsx:101]: foward ref imported here. its bleeding a bit because this ideally would be in the styled visitor - but that doesnt have any knowledge of the program and i didn't really want to do more work.

we could move it in though.

File: packages/babel-plugin/src/types.tsx [hunk 6]
```diff
@@ -1,20 +1,29 @@
...
+   * Will import the React namespace if it is missing.
+   * When using the `'automatic'` jsx runtime set this to `false`.
+   *
+   * Defaults to `true`.
+   */
+  importReact?: boolean;
 }
 
-export interface State {
+export interface State extends PluginPass {
```
Comment (madou) [inline packages/babel-plugin/src/types.tsx:26]: realized plugin pass is the type for this.

File: packages/babel-plugin/src/index.tsx (hunk 5 above)
Comment (pgmanutd) [reply packages/babel-plugin/src/index.tsx:101]: Yes later please

**Comment by pgmanutd** [comment]
@madou: Heading out. Will review it once m back. Seems like you just reviewed your own PR 😆

**Comment by pgmanutd** [comment]
> @madou: Heading out. Will review it once m back. Seems like you just reviewed your own PR 😆

Sorry was bit busy today. Will review this in morning 😃

File: packages/babel-plugin/src/index.tsx (hunk 5 above)
Comment (madou) [reply packages/babel-plugin/src/index.tsx:101]: created this https://github.com/atlassian-labs/compiled/issues/424

**Review by DarkPurple141 — DISMISSED** [review]
LGTM

**Review by DarkPurple141 — APPROVED** [review]
get good
