### PR TITLE
fix: fixes hard coded usage of styled import specifier

### LINKED ISSUE #256: Remove hardcoded 'styled' check for 'local.name'
Replace `local.name` with `imported.name` [here](https://github.com/atlassian-labs/compiled/blob/023d2f5afefa659a7ab0787af1ea0ab648f3a89f/packages/babel-plugin/src/index.tsx#L20). 

Why? because when codemoded, original code

`import styledFunction from '@emotion/styled';` 

will be converted to

`import { styled as styledFunction } from '@compiled/css-in-js';`

Please think of other scenarios we can have here.

### PR DESCRIPTION
**Pull request by madou**
Closes #256

### CODE REVIEW

**Comment by madou** [comment]
@pgmanutd please review :)

**Comment by pgmanutd** [comment]
> @pgmanutd please review :)

Will review today. Sorry didn't get time yesterday.

File: packages/babel-plugin/src/index.tsx [hunk 1]
```diff
@@ -13,39 +14,52 @@ export default declare<State>((api) => {
...
-            )
+            .filter((specifier) => {
+              if (!state.compiledImports || !t.isImportSpecifier(specifier)) {
+                return false;
+              }
+
+              if (specifier.imported.name === 'styled') {
+                state.compiledImports.styled = specifier.local.name;
+                // Remove the import
+                return false;
```
Comment (pgmanutd) [inline packages/babel-plugin/src/index.tsx:37]: nit: Are we concerned about loop performance? Coz we can do `.find` and `.filter` separately for readability may be. Otherwise this looks cool 🎉

File: packages/babel-plugin/src/index.tsx [hunk 2]
```diff
@@ -13,39 +14,52 @@ export default declare<State>((api) => {
...
+              // Keep the import
+              return true;
+            })
+            // Add on the util imports we're going to use later in the transform.
             .concat([importSpecifier('CC'), importSpecifier('CS')]);
         }
       },
       TaggedTemplateExpression(path, state) {
-        if (!state.compiledImportFound) {
+        if (!state.compiledImports?.styled) {
```
Comment (pgmanutd) [inline packages/babel-plugin/src/index.tsx:48]: Optional chaining is dope. I remember from coffescript days how we used to do this. It was awesome. This is the one I am talking about http://coffeescript.org/#existential-operator

**Review by pgmanutd — DISMISSED** [review]

File: packages/babel-plugin/src/index.tsx (hunk 1 above)
Comment (madou) [reply packages/babel-plugin/src/index.tsx:37]: thanks!

honestly we might be concerned - we'll find out later when we roll out to Jira 😓

File: packages/babel-plugin/src/index.tsx [hunk 3]
```diff
@@ -13,39 +14,52 @@ export default declare<State>((api) => {
...
+          state.compiledImports = {};
+
           path.node.specifiers = path.node.specifiers
-            .filter(
-              (specifier) =>
-                specifier.local.name !== 'styled' && specifier.local.name !== 'ClassNames'
-            )
+            .filter((specifier) => {
+              if (!state.compiledImports || !t.isImportSpecifier(specifier)) {
+                return false;
```
Comment (madou) [inline packages/babel-plugin/src/index.tsx:31]: @pgmanutd we might want to return `true` just in case - i'll update the code

Comment (madou) [reply packages/babel-plugin/src/index.tsx]: done - check the latest commit

File: packages/babel-plugin/src/index.tsx [hunk 4]
```diff
@@ -13,39 +14,55 @@ export default declare<State>((api) => {
...
           }
         },
       },
       ImportDeclaration(path, state) {
-        if (path.node.source.value === '@compiled/core') {
-          state.compiledImportFound = true;
-          path.node.specifiers = path.node.specifiers
-            .filter(
-              (specifier) =>
-                specifier.local.name !== 'styled' && specifier.local.name !== 'ClassNames'
```
[the remark this answers is not in the document]
Comment (madou) [reply packages/babel-plugin/src/index.tsx:28]: i figured since its not implemented we just remove it for now

**Review by pgmanutd — APPROVED** [review]
